version: '3.6'

services:
  api:
    build: api_gateway/.
    command:
      - api_gateway/docker-entrypoint.sh
    depends_on:
      - micro_service_grpc
      - micro_service_rmp
      - rabbitmq
    volumes:
      - api_gateway:/usr/src/app
    ports:
      - 1337:1337
    networks:
      - default
    environment:
      - ENV=dev
  micro_service_qrpc:
    image: golang
    restart: always
    ports:
      - "8100:8100"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db
  micro_service_rmq:
    image: golang
    restart: always
    ports:
      - "8100:8100"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge