openapi: 3.0.3
info:
  title: Unified Availability Service ${stage}
  version: '1.0'
servers:
  - url: http://localhost:{port}
    description: Local development server
    variables:
      port:
        default: '5010'
  - url: https://unified-availability-service.api.qa.patientpop.com
    description: QA server
  - url: https://unified-availability-service.api.stg.patientpop.com
    description: Staging server
  - url: https://unified-availability-service.api.patientpop.com
    description: Production server
paths:
  /v1/status:
    get:
      summary: Retrieve service status
      parameters: [ ]
      responses:
        '200':
          description: Service Available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
      description: Retrieve service status
      security:
        - apiKey: [ ]
      operationId: get_status
      x-openapi-router-controller: src.status.controllers.v1
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
        uri: ${network_lb_path}/v1/status
        connectionType: VPC_LINK
        connectionId: ${vpc_link}
        httpMethod: GET
        type: HTTP_PROXY
      tags:
        - status
  /v1/status:
    get:
      summary: Retrieve service status
      parameters: [ ]
      responses:
        '200':
          description: Service Available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
      description: Retrieve service status
      security:
        - apiKey: [ ]
      operationId: get_status
      x-openapi-router-controller: src.status.controllers.v1
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
        uri: ${network_lb_path}/v1/status
        connectionType: VPC_LINK
        connectionId: ${vpc_link}
        httpMethod: GET
        type: HTTP_PROXY
      tags:
        - status

