version: '3.1'
services:
  file_server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "2049:2049"
    cap_add:
      - SYS_ADMIN
    environment:
     NFS_LOG_LEVEL: DEBUG
    